name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check conventinal commits
        uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true
      - name: Generate Changelog
        run: 'cog changelog --at ${{ github.ref }}'
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: tg-notify

permissions:
  contents: write
