name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Release
        uses: softprops/action-gh-release@2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tg-notify
